apex-mdapi/src/objects/Form__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubmitLabel__c</fullName>
        <defaultValue>&apos;Conferma&apos;</defaultValue>
        <label>Submit Label</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SuccessMessage__c</fullName>
        <defaultValue>&apos;Grazie per aver compilato il form.&apos;</defaultValue>
        <label>Success Message</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

apex-mdapi/src/objects/FormField__c.object
<CustomObject>
    <fields>
        <fullName>ResponseOf__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ResponseOf</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Value</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>FormResponse__c</referenceTo>
        <relationshipLabel>Response</relationshipLabel>
        <relationshipName>FormFields</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Form Field</label>
    <nameField>
        <label>Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Fields</pluralLabel>
    <recordTypes>
        <fullName>Value</fullName>
        <active>true</active>
        <label>Value</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

apex-mdapi/src/objects/FormResponse__c.object
<CustomObject>
    <fields>
        <fullName>ResponseOfForm__c</fullName>
        <label>ResponseOfForm</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Form Responses</relationshipLabel>
        <relationshipName>FormResponses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>FormResponses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Form Response</label>
    <nameField>
        <label>Form Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

apex-mdapi/src/classes/FormViewerController.cls
/**
 * Created by wnardo on 9/2/2022.
 */

public with sharing class FormViewerController {

	@AuraEnabled
	public static FormContext retrieveFormDefinition(String id){
		List<Form__c> forms = FormDAO.retrieveForm(id);
		if(forms.isEmpty()){
			return FormContext.inexistent();
		}
		Form__c form = forms[0];
		if(!form.Active__c){
			return FormContext.inexistent();
		}

		FormContext context = new FormContext();
		context.title = form.Name;
		context.successMessage = form.SuccessMessage__c;
		context.submitLabel = form.SubmitLabel__c;
		context.submitted = !FormDAO.retrieveFormResponseByFormAndUser(id).isEmpty();
		context.definitions = FormDAO.retrieveFormDefinition(id);
		return context;
	}

	@AuraEnabled
	public static List<FormField__c> retrieveFormResponse(String id){
		return FormDAO.retrieveFormResponse(id);
	}

	@AuraEnabled
	public static Boolean saveFormResponse(String formId, List<FormEntry> response){
		try{
			Map<Id,FormField__c> definitions = new Map<Id,FormField__c>(FormDAO.retrieveFormDefinition(formId));

			FormResponse__c formResponse = createFormResponse(formId);

			List<FormField__c> fieldRes = new List<FormField__c>();
			for(FormEntry e : response){
				FormField__c def = definitions.get(e.identifier);
				fieldRes.add(createFieldRes(def, e, formResponse));
			}

			insert fieldRes;
			return true;
		} catch(Exception e){
			System.debug(e.getMessage());
			return false;
		}
	}

	private static FormField__c createFieldRes(FormField__c def, FormEntry e, FormResponse__c formResponse) {
		FormField__c res = def.clone();
		res.RecordTypeId = FormConstants.VALUE_RTID;
		res.Response__c = e.value;
		res.ResponseOf__c = formResponse.Id;
		return res;
	}

	private static FormResponse__c createFormResponse(String formId) {
		User usr = [SELECT Id, Name FROM User WHERE Id = :UserInfo.getUserId()];
		FormResponse__c formResponse = new FormResponse__c();
		formResponse.Name = 'Response Of ' + usr.Name;
		formResponse.ResponseOfForm__c = formId;
		formResponse.User__c = usr.Id;

		insert formResponse;

		return formResponse;
	}

}