apex-mdapi/src/objects/Form__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubmitLabel__c</fullName>
        <defaultValue>&apos;Conferma&apos;</defaultValue>
        <label>Submit Label</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SuccessMessage__c</fullName>
        <defaultValue>&apos;Grazie per aver compilato il form.&apos;</defaultValue>
        <label>Success Message</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

apex-mdapi/src/objects/FormField__c.object
<CustomObject>
    <fields>
        <fullName>DefaultValue__c</fullName>
        <label>Default Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DefinitionOfForm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DefinitionOfForm</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only Definition type are allowed here</errorMessage>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Definition</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Definitions</relationshipLabel>
        <relationshipName>FormFields</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Readonly__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Readonly</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ResponseOf__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ResponseOf</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Value</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>FormResponse__c</referenceTo>
        <relationshipLabel>Response</relationshipLabel>
        <relationshipName>FormFields</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>text</fullName>
                </value>
                <value>
                    <fullName>number</fullName>
                </value>
                <value>
                    <fullName>email</fullName>
                </value>
                <value>
                    <fullName>checkbox</fullName>
                </value>
                <value>
                    <fullName>date</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Form Field</label>
    <nameField>
        <label>Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

apex-mdapi/src/objects/FormResponse__c.object
<CustomObject>
    <fields>
        <fullName>ResponseOfForm__c</fullName>
        <label>ResponseOfForm</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Form Responses</relationshipLabel>
        <relationshipName>FormResponses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>FormResponses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Form Response</label>
    <nameField>
        <label>Form Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

apex-mdapi/src/classes/FormDAO.cls
/**
 * Created by wnardo on 9/2/2022.
 */

public inherited sharing class FormDAO {

	public static List<FormField__c> retrieveFormDefinition(String formId){
		return [
			SELECT Id, Name, Type__c, Required__c, Order__c, Readonly__c, DefaultValue__c
			FROM FormField__c
			WHERE DefinitionOfForm__c = :formId ORDER BY Order__c
		];
	}

	public static List<Form__c> retrieveForm(String formId){
		return  [
			SELECT Id, Name, SuccessMessage__c, Active__c, SubmitLabel__c
			FROM Form__c
			WHERE Active__c = TRUE AND Id = :formId
		];
	}

	public static List<FormField__c> retrieveFormsDefinition(Set<Id> formIds){
		return [
			SELECT Id, Name, Type__c, Required__c, Order__c, DefinitionOfForm__c, Readonly__c, DefaultValue__c
			FROM FormField__c
			WHERE DefinitionOfForm__c IN :formIds
		];
	}

	public static List<FormField__c> retrieveFormResponse(String resId){
		return [
			SELECT Id, Name, Response__c
			FROM FormField__c
			WHERE ResponseOf__c = :resId ORDER BY Order__c
		];
	}

	public static List<FormResponse__c> retrieveFormResponseByFormAndUser(String formId){
		return [
			SELECT Id
			FROM FormResponse__c
			WHERE User__c = :UserInfo.getUserId() AND ResponseOfForm__c = :formId
		];
	}

}