apex-mdapi/src/objects/Form__c.object
<CustomObject>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

apex-mdapi/src/objects/FormField__c.object
<CustomObject>
    <fields>
        <fullName>DefinitionOfForm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DefinitionOfForm</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only Definition type are allowed here</errorMessage>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Definition</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Definitions</relationshipLabel>
        <relationshipName>FormFields</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ResponseOf__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ResponseOf</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Value</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>FormResponse__c</referenceTo>
        <relationshipLabel>Response</relationshipLabel>
        <relationshipName>FormFields</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Form Field</label>
    <nameField>
        <label>Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

apex-mdapi/src/classes/TriggerFormImpl.cls
/**
 * Created by wnardo on 9/2/2022.
 */

public inherited sharing class TriggerFormImpl extends AbstractTrigger  {

	public override String getClassName() {
		return TriggerFormFieldImpl.class.getName();
	}

	protected override void doBeforeDelete() {
		List<Form__c> forms = Trigger.old;
		deleteRelatedFormField(forms);
	}

	private void deleteRelatedFormField(List<Form__c> forms) {
		Set<Id> formId = new Set<Id>();
		for(Form__c f : forms) {
			formId.add(f.Id);
		}

		delete [
			SELECT Id
			FROM FormField__c
			WHERE DefinitionOfForm__c IN :formId OR ResponseOf__c IN :formId
		];
	}
}